#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <limits.h>
#include <conio.h>
#include <stdlib.h>
#include <i86.h>
#include <io.h>
//#include <string.h>
#include <mem.h>
#include <dos.h>
#include <fcntl.h>
#include <bios.h>
#include <malloc.h>
#include <math.h>
#include <ctype.h>
#include <direct.h>
#include "graphics.h"
#include "mydos.h"
#include "type.h"
#include "const.h"

#ifndef _VAR_C_
   #include "ext.h"
#endif

//---- function proto ----
#include "uiProto.h"
#include "..\kernl\knlProto.h"
#include "..\editor\edtProto.h"
#include "..\image\imgProto.h"
#include "..\format\fmtProto.h"
